//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E33Randomizer.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("E33Randomizer.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Terminology_Encounter {
            get {
                return ResourceManager.GetString("Terminology_Encounter", resourceCulture);
            }
        }
        
        public static string Terminology_Encounter_size {
            get {
                return ResourceManager.GetString("Terminology_Encounter size", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyArchetype {
            get {
                return ResourceManager.GetString("Terminology_EnemyArchetype", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyCategory {
            get {
                return ResourceManager.GetString("Terminology_EnemyCategory", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyLoot {
            get {
                return ResourceManager.GetString("Terminology_EnemyLoot", resourceCulture);
            }
        }
        
        public static string Terminology_Check {
            get {
                return ResourceManager.GetString("Terminology_Check", resourceCulture);
            }
        }
        
        public static string Terminology_CheckSizeNumber {
            get {
                return ResourceManager.GetString("Terminology_CheckSizeNumber", resourceCulture);
            }
        }
        
        public static string Terminology_ItemQuantity {
            get {
                return ResourceManager.GetString("Terminology_ItemQuantity", resourceCulture);
            }
        }
        
        public static string Terminology_MerchantUnlocks {
            get {
                return ResourceManager.GetString("Terminology_MerchantUnlocks", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeEncounterSizes {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeEncounterSizes", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeEncounterSizes {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeEncounterSizes", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ChangeSizeOfEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ChangeSizeOfEncounters", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ChangeSizeOfEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ChangeSizeOfEncounters", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeMerchantFights {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeMerchantFights", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeMerchantFights {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeMerchantFights", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeMerchantFights_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeMerchantFights_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_IncludeCutContent {
            get {
                return ResourceManager.GetString("Randomize_Enemies_IncludeCutContent", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_IncludeCutContent {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_IncludeCutContent", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_IncludeCutContent_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_IncludeCutContent_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_EnableEnemyOnslaught {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_EnableEnemyOnslaught", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_RandomizeAddedEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_RandomizeAddedEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_NumbeOfAdditionalEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_NumbeOfAdditionalEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_CapEncounterSizesAt {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_CapEncounterSizesAt", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnsureEncountersAtLeastOne {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnsureEncountersAtLeastOne", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_EnsureEncountersAtLeastOne {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_EnsureEncountersAtLeastOne", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ReduceBossRepetition {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ReduceBossRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReduceBossRepetition {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReduceBossRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ReplacePhase2Simon {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ReplacePhase2Simon", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2Simon {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2Simon", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Lune {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Lune", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Eveque {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Eveque", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Goblu {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Goblu", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_UltimateSakapatate {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_UltimateSakapatate", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_GestralTournament {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_GestralTournament", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Never {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Never", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Button_EditEnemyPlacements {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Button_EditEnemyPlacements", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Button_EditIndividualEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Button_EditIndividualEncounters", resourceCulture);
            }
        }
        
        public static string Main_RandomizeItems {
            get {
                return ResourceManager.GetString("Main_RandomizeItems", resourceCulture);
            }
        }
        
        public static string Main_MakeEveryItemShowNotification {
            get {
                return ResourceManager.GetString("Main_MakeEveryItemShowNotification", resourceCulture);
            }
        }
        
        public static string Main_IncludeCutContentItems {
            get {
                return ResourceManager.GetString("Main_IncludeCutContentItems", resourceCulture);
            }
        }
        
        public static string Main_ReceivePaintedPowerActIII {
            get {
                return ResourceManager.GetString("Main_ReceivePaintedPowerActIII", resourceCulture);
            }
        }
        
        public static string Main_RandomizeStartingWeaponsCosmetics {
            get {
                return ResourceManager.GetString("Main_RandomizeStartingWeaponsCosmetics", resourceCulture);
            }
        }
        
        public static string Main_RandomizeEsquieRocksMapPickups {
            get {
                return ResourceManager.GetString("Main_RandomizeEsquieRocksMapPickups", resourceCulture);
            }
        }
        
        public static string Main_LimitEsquiesRocksOriginalAreas {
            get {
                return ResourceManager.GetString("Main_LimitEsquiesRocksOriginalAreas", resourceCulture);
            }
        }
        
        public static string Main_RandomizeEnemyFeetDrops {
            get {
                return ResourceManager.GetString("Main_RandomizeEnemyFeetDrops", resourceCulture);
            }
        }
        
        public static string Main_EnableGearRollsInPrologue {
            get {
                return ResourceManager.GetString("Main_EnableGearRollsInPrologue", resourceCulture);
            }
        }
        
        public static string Main_RandomizeGestralBeachRewards {
            get {
                return ResourceManager.GetString("Main_RandomizeGestralBeachRewards", resourceCulture);
            }
        }
        
        public static string Main_ChangeNumberItemsNonRandomizedChecks {
            get {
                return ResourceManager.GetString("Main_ChangeNumberItemsNonRandomizedChecks", resourceCulture);
            }
        }
        
        public static string Main_ReduceKeyItemRepetition {
            get {
                return ResourceManager.GetString("Main_ReduceKeyItemRepetition", resourceCulture);
            }
        }
        
        public static string Main_MakeAnyMerchantWaresLocked {
            get {
                return ResourceManager.GetString("Main_MakeAnyMerchantWaresLocked", resourceCulture);
            }
        }
        
        public static string Main_RandomizeCheckSizes {
            get {
                return ResourceManager.GetString("Main_RandomizeCheckSizes", resourceCulture);
            }
        }
        
        public static string Main_RandomizeQuantitiesUpgradeMaterials {
            get {
                return ResourceManager.GetString("Main_RandomizeQuantitiesUpgradeMaterials", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_PresetJSON {
            get {
                return ResourceManager.GetString("CustomPlacement_PresetJSON", resourceCulture);
            }
        }
        
        public static string CustomPlacement_LoadSavePresetJSON {
            get {
                return ResourceManager.GetString("CustomPlacement_LoadSavePresetJSON", resourceCulture);
            }
        }
        
        public static string ToolTip_Header_HowItWorks {
            get {
                return ResourceManager.GetString("ToolTip_Header_HowItWorks", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_Excluded", resourceCulture);
            }
        }
        
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_SelectCategory {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_SelectCategory", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_IsReplacedBy {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_IsReplacedBy", resourceCulture);
            }
        }
        
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        public static string ToolTip_Remove {
            get {
                return ResourceManager.GetString("ToolTip_Remove", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_AddPlacementRow {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_AddPlacementRow", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_AddFrequencyRow {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_AddFrequencyRow", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_AddCustomPlacements {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_AddCustomPlacements", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_SpecialRules {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_SpecialRules", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_FrequencyAdjustments {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_FrequencyAdjustments", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_Adjustments {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_Adjustments", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_LoadPresetJson {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_LoadPresetJson", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_SavePresetJson {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_SavePresetJson", resourceCulture);
            }
        }
        
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
    }
}
