//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E33Randomizer.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("E33Randomizer.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Terminology_Encounter {
            get {
                return ResourceManager.GetString("Terminology_Encounter", resourceCulture);
            }
        }
        
        public static string Terminology_Encounter_size {
            get {
                return ResourceManager.GetString("Terminology_Encounter size", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyArchetype {
            get {
                return ResourceManager.GetString("Terminology_EnemyArchetype", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyCategory {
            get {
                return ResourceManager.GetString("Terminology_EnemyCategory", resourceCulture);
            }
        }
        
        public static string Terminology_EnemyLoot {
            get {
                return ResourceManager.GetString("Terminology_EnemyLoot", resourceCulture);
            }
        }
        
        public static string Terminology_Check {
            get {
                return ResourceManager.GetString("Terminology_Check", resourceCulture);
            }
        }
        
        public static string Terminology_CheckSizeNumber {
            get {
                return ResourceManager.GetString("Terminology_CheckSizeNumber", resourceCulture);
            }
        }
        
        public static string Terminology_ItemQuantity {
            get {
                return ResourceManager.GetString("Terminology_ItemQuantity", resourceCulture);
            }
        }
        
        public static string Terminology_MerchantUnlocks {
            get {
                return ResourceManager.GetString("Terminology_MerchantUnlocks", resourceCulture);
            }
        }
        
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        public static string Button_Tooltip_CopyToClipboard {
            get {
                return ResourceManager.GetString("Button_Tooltip_CopyToClipboard", resourceCulture);
            }
        }
        
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeEncounterSizes {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeEncounterSizes", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeEncounterSizes {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeEncounterSizes", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ChangeSizeOfEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ChangeSizeOfEncounters", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ChangeSizeOfEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ChangeSizeOfEncounters", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeMerchantFights {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeMerchantFights", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_RandomizeMerchantFights {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_RandomizeMerchantFights", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_RandomizeMerchantFights_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_RandomizeMerchantFights_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_IncludeCutContent {
            get {
                return ResourceManager.GetString("Randomize_Enemies_IncludeCutContent", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_IncludeCutContent {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_IncludeCutContent", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_IncludeCutContent_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_IncludeCutContent_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_EnableEnemyOnslaught {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_EnableEnemyOnslaught", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_Note {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_Note", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_RandomizeAddedEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_RandomizeAddedEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_NumberOfAdditionalEnemies {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_NumberOfAdditionalEnemies", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnableEnemyOnslaught_CapEncounterSizesAt {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnableEnemyOnslaught_CapEncounterSizesAt", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_EnsureEncountersAtLeastOne {
            get {
                return ResourceManager.GetString("Randomize_Enemies_EnsureEncountersAtLeastOne", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_EnsureEncountersAtLeastOne {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_EnsureEncountersAtLeastOne", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ReduceBossRepetition {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ReduceBossRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReduceBossRepetition {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReduceBossRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_ReplacePhase2Simon {
            get {
                return ResourceManager.GetString("Randomize_Enemies_ReplacePhase2Simon", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2Simon {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2Simon", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Lune {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Lune", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Eveque {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Eveque", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Goblu {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Goblu", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_UltimateSakapatate {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_UltimateSakapatate", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_GestralTournament {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_GestralTournament", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Never {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Tooltip_ReplacePhase2SimonUntilAfter_Never", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Button_EditEnemyPlacements {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Button_EditEnemyPlacements", resourceCulture);
            }
        }
        
        public static string Randomize_Enemies_Button_EditIndividualEncounters {
            get {
                return ResourceManager.GetString("Randomize_Enemies_Button_EditIndividualEncounters", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeItems {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeItems", resourceCulture);
            }
        }
        
        public static string Randomize_Items_MakeEveryItemShowAPickUpNotification {
            get {
                return ResourceManager.GetString("Randomize_Items_MakeEveryItemShowAPickUpNotification", resourceCulture);
            }
        }
        
        public static string Randomize_Items_IncludeCutContentItems {
            get {
                return ResourceManager.GetString("Randomize_Items_IncludeCutContentItems", resourceCulture);
            }
        }
        
        public static string Randomize_Items_ReceivePaintedPowerAtTheStartOfActIII {
            get {
                return ResourceManager.GetString("Randomize_Items_ReceivePaintedPowerAtTheStartOfActIII", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeStartingWeapons {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeStartingWeapons", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeStartingCosmetics {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeStartingCosmetics", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeEsquiesRocksIntoMapPickups {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeEsquiesRocksIntoMapPickups", resourceCulture);
            }
        }
        
        public static string Randomize_Items_LimitEsquiesRocksToOnlyTheirOriginalAreas {
            get {
                return ResourceManager.GetString("Randomize_Items_LimitEsquiesRocksToOnlyTheirOriginalAreas", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeEnemyFeetDrops {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeEnemyFeetDrops", resourceCulture);
            }
        }
        
        public static string Randomize_Items_EnableGearRollsInPrologue {
            get {
                return ResourceManager.GetString("Randomize_Items_EnableGearRollsInPrologue", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeGestralBeachRewards {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeGestralBeachRewards", resourceCulture);
            }
        }
        
        public static string Randomize_Items_ChangeNumberOfItemsInNonRandomizedChecks {
            get {
                return ResourceManager.GetString("Randomize_Items_ChangeNumberOfItemsInNonRandomizedChecks", resourceCulture);
            }
        }
        
        public static string Randomize_Items_ReduceKeyItemRepetition {
            get {
                return ResourceManager.GetString("Randomize_Items_ReduceKeyItemRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Items_ReduceGearRepetition {
            get {
                return ResourceManager.GetString("Randomize_Items_ReduceGearRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Items_MakeAnyOfTheMerchantWaresLockedWithProbability {
            get {
                return ResourceManager.GetString("Randomize_Items_MakeAnyOfTheMerchantWaresLockedWithProbability", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeMerchantInventorySizesBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeMerchantInventorySizesBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeNumberOfLootDropsBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeNumberOfLootDropsBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeNumberOfTheEndlessTowerRewardsBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeNumberOfTheEndlessTowerRewardsBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeNumberOfItemsPerMapPickupBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeNumberOfItemsPerMapPickupBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeNumberOfCutsceneRewardsBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeNumberOfCutsceneRewardsBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_RandomizeQuantitiesOfUpgradeMaterialsBetween {
            get {
                return ResourceManager.GetString("Randomize_Items_RandomizeQuantitiesOfUpgradeMaterialsBetween", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Button_CustomizeItemPlacements {
            get {
                return ResourceManager.GetString("Randomize_Items_Button_CustomizeItemPlacements", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Button_EditIndividualChecks {
            get {
                return ResourceManager.GetString("Randomize_Items_Button_EditIndividualChecks", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeItems {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeItems", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_MakeEveryItemShowAPickUpNotification {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_MakeEveryItemShowAPickUpNotification", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_IncludeCutContentItems {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_IncludeCutContentItems", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_ReceivePaintedPowerAtTheStartOfActIII {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_ReceivePaintedPowerAtTheStartOfActIII", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeStartingWeapons {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeStartingWeapons", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeStartingCosmetics {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeStartingCosmetics", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeEsquiesRocksIntoMapPickups {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeEsquiesRocksIntoMapPickups", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_LimitEsquiesRocksToOnlyTheirOriginalArea {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_LimitEsquiesRocksToOnlyTheirOriginalArea", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeEnemyFeetDrops {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeEnemyFeetDrops", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_EnableGearRollsInPrologue {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_EnableGearRollsInPrologue", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeGestralBeachRewards {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeGestralBeachRewards", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_ChangeNumberOfItemsInNonRandomizedChecks {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_ChangeNumberOfItemsInNonRandomizedChecks", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_ReduceKeyItemRepetition {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_ReduceKeyItemRepetition", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_MakeAnyOfTheMerchantWaresLocked {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_MakeAnyOfTheMerchantWaresLocked", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeVariousCheckSizes {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeVariousCheckSizes", resourceCulture);
            }
        }
        
        public static string Randomize_Items_Tooltip_RandomizeQuantitiesOfUpgradeMaterials {
            get {
                return ResourceManager.GetString("Randomize_Items_Tooltip_RandomizeQuantitiesOfUpgradeMaterials", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_RandomizeSkills {
            get {
                return ResourceManager.GetString("Randomize_Skills_RandomizeSkills", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ReduceSkillDuplication {
            get {
                return ResourceManager.GetString("Randomize_Skills_ReduceSkillDuplication", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_RandomizeSkillUnlockCosts {
            get {
                return ResourceManager.GetString("Randomize_Skills_RandomizeSkillUnlockCosts", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_UnlockFullGustaveSkillTree {
            get {
                return ResourceManager.GetString("Randomize_Skills_UnlockFullGustaveSkillTree", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_GuaranteeThatGustaveStartsWithOvercharge {
            get {
                return ResourceManager.GetString("Randomize_Skills_GuaranteeThatGustaveStartsWithOvercharge", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_MakeAllSkillsUnlockedByItemsInsteadOfSkillPoints {
            get {
                return ResourceManager.GetString("Randomize_Skills_MakeAllSkillsUnlockedByItemsInsteadOfSkillPoints", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_RandomizeSkillTreeLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_RandomizeSkillTreeLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_UseFullyRandomNodeLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_UseFullyRandomNodeLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ChangeTheNumberOfLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_ChangeTheNumberOfLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_SetTheLinkDensity {
            get {
                return ResourceManager.GetString("Randomize_Skills_SetTheLinkDensity", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_LinksNode {
            get {
                return ResourceManager.GetString("Randomize_Skills_LinksNode", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_RandomizeSkills {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_RandomizeSkills", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_ReduceSkillDuplication {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_ReduceSkillDuplication", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_RandomizeSkillUnlockCosts {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_RandomizeSkillUnlockCosts", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_UnlockFullGustaveSkillTree {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_UnlockFullGustaveSkillTree", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_GuaranteeThatGustaveStartsWithOvercharge {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_GuaranteeThatGustaveStartsWithOvercharge", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_MakeAllSkillsUnlockedByItemsInsteadOfSkillPoints {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_MakeAllSkillsUnlockedByItemsInsteadOfSkillPoints", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_RandomizeSkillTreeLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_RandomizeSkillTreeLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_UseFullyRandomNodeLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_UseFullyRandomNodeLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_ChangeTheNumberOfLinks {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_ChangeTheNumberOfLinks", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_ToolTip_SetTheLinkDensity {
            get {
                return ResourceManager.GetString("Randomize_Skills_ToolTip_SetTheLinkDensity", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_Button_CustomizeItemPlacements {
            get {
                return ResourceManager.GetString("Randomize_Skills_Button_CustomizeItemPlacements", resourceCulture);
            }
        }
        
        public static string Randomize_Skills_Button_EditIndividualSkillTrees {
            get {
                return ResourceManager.GetString("Randomize_Skills_Button_EditIndividualSkillTrees", resourceCulture);
            }
        }
        
        public static string Randomize_Locations_Button_CustomizeLocationPlacements {
            get {
                return ResourceManager.GetString("Randomize_Locations_Button_CustomizeLocationPlacements", resourceCulture);
            }
        }
        
        public static string Randomize_Locations_Button_EditIndividualLocations {
            get {
                return ResourceManager.GetString("Randomize_Locations_Button_EditIndividualLocations", resourceCulture);
            }
        }
        
        public static string Misc_SaveFile_Header {
            get {
                return ResourceManager.GetString("Misc_SaveFile_Header", resourceCulture);
            }
        }
        
        public static string Misc_SaveFile_AddCounters_Description {
            get {
                return ResourceManager.GetString("Misc_SaveFile_AddCounters_Description", resourceCulture);
            }
        }
        
        public static string Misc_SaveFile_Button_AddCounters {
            get {
                return ResourceManager.GetString("Misc_SaveFile_Button_AddCounters", resourceCulture);
            }
        }
        
        public static string Misc_SaveFile_FixCurtain_Description {
            get {
                return ResourceManager.GetString("Misc_SaveFile_FixCurtain_Description", resourceCulture);
            }
        }
        
        public static string Misc_SaveFile_Button_FixCurtains {
            get {
                return ResourceManager.GetString("Misc_SaveFile_Button_FixCurtains", resourceCulture);
            }
        }
        
        public static string Main_Tab_EnemyRandomizer {
            get {
                return ResourceManager.GetString("Main_Tab_EnemyRandomizer", resourceCulture);
            }
        }
        
        public static string Main_Tab_ItemRandomizer {
            get {
                return ResourceManager.GetString("Main_Tab_ItemRandomizer", resourceCulture);
            }
        }
        
        public static string Main_Tab_SkillRandomizer {
            get {
                return ResourceManager.GetString("Main_Tab_SkillRandomizer", resourceCulture);
            }
        }
        
        public static string Main_Tab_LocationRandomizer {
            get {
                return ResourceManager.GetString("Main_Tab_LocationRandomizer", resourceCulture);
            }
        }
        
        public static string Main_Tab_Misc {
            get {
                return ResourceManager.GetString("Main_Tab_Misc", resourceCulture);
            }
        }
        
        public static string Main_Button_Save {
            get {
                return ResourceManager.GetString("Main_Button_Save", resourceCulture);
            }
        }
        
        public static string Main_Button_Load {
            get {
                return ResourceManager.GetString("Main_Button_Load", resourceCulture);
            }
        }
        
        public static string Main_Button_GenerateAndPack {
            get {
                return ResourceManager.GetString("Main_Button_GenerateAndPack", resourceCulture);
            }
        }
        
        public static string Main_Seed {
            get {
                return ResourceManager.GetString("Main_Seed", resourceCulture);
            }
        }
        
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Enemy_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Enemy_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Item_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Item_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Skill_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Skill_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_Excluded", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_CustomPlacement {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_CustomPlacement", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_FrequencyAdjustment {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_FrequencyAdjustment", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Location_Title {
            get {
                return ResourceManager.GetString("CustomPlacement_Location_Title", resourceCulture);
            }
        }
        
        public static string CustomPlacement_PresetJSON {
            get {
                return ResourceManager.GetString("CustomPlacement_PresetJSON", resourceCulture);
            }
        }
        
        public static string CustomPlacement_LoadSavePresetJSON {
            get {
                return ResourceManager.GetString("CustomPlacement_LoadSavePresetJSON", resourceCulture);
            }
        }
        
        public static string ToolTip_Header_HowItWorks {
            get {
                return ResourceManager.GetString("ToolTip_Header_HowItWorks", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_NotRandomized {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_NotRandomized", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_Excluded {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_Excluded", resourceCulture);
            }
        }
        
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_SelectCategory {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_SelectCategory", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_IsReplacedBy {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_IsReplacedBy", resourceCulture);
            }
        }
        
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        public static string ToolTip_Remove {
            get {
                return ResourceManager.GetString("ToolTip_Remove", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_AddPlacementRow {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_AddPlacementRow", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_AddFrequencyRow {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_AddFrequencyRow", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_AddCustomPlacements {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_AddCustomPlacements", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_SpecialRules {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_SpecialRules", resourceCulture);
            }
        }
        
        public static string CustomPlacement_TabItem_FrequencyAdjustments {
            get {
                return ResourceManager.GetString("CustomPlacement_TabItem_FrequencyAdjustments", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Header_Adjustments {
            get {
                return ResourceManager.GetString("CustomPlacement_Header_Adjustments", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_QuickPresets {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_QuickPresets", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_LoadPresetJson {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_LoadPresetJson", resourceCulture);
            }
        }
        
        public static string CustomPlacement_Button_SavePresetJson {
            get {
                return ResourceManager.GetString("CustomPlacement_Button_SavePresetJson", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Button_Reroll {
            get {
                return ResourceManager.GetString("IndividualContainers_Button_Reroll", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Button_GenerateModFiles {
            get {
                return ResourceManager.GetString("IndividualContainers_Button_GenerateModFiles", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Title {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Title", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Tooltip_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Tooltip_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_AddObject {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_AddObject", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Tooltip_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Tooltip_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_LoadTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_LoadTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_SaveTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_SaveTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Enemy_Search {
            get {
                return ResourceManager.GetString("IndividualContainers_Enemy_Search", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Title {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Title", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Tooltip_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Tooltip_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_AddObject {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_AddObject", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Tooltip_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Tooltip_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_LoadTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_LoadTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_SaveTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_SaveTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Item_Search {
            get {
                return ResourceManager.GetString("IndividualContainers_Item_Search", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Title {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Title", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Tooltip_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Tooltip_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_AddObject {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_AddObject", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Tooltip_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Tooltip_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_LoadTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_LoadTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_SaveTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_SaveTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Skill_Search {
            get {
                return ResourceManager.GetString("IndividualContainers_Skill_Search", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Title {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Title", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Tooltip_Containers {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Tooltip_Containers", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_AddObject {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_AddObject", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Tooltip_Objects {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Tooltip_Objects", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_LoadTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_LoadTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_SaveTxt {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_SaveTxt", resourceCulture);
            }
        }
        
        public static string IndividualContainers_Location_Search {
            get {
                return ResourceManager.GetString("IndividualContainers_Location_Search", resourceCulture);
            }
        }
    }
}
